// Generated by CoffeeScript 1.9.3
(function() {
  var baseURL, buildQuery;

  baseURL = 'https://marginal-review-api.herokuapp.com/api/v1/reviews';

  $(document).ready(function() {
    var $contentDiv, $searchBoxAuthor, $searchBoxGenre, $searchBoxTitle, $submitButton;
    $contentDiv = $('#content');
    $searchBoxGenre = $('#searchBoxGenre');
    $searchBoxTitle = $('#searchBoxTitle');
    $searchBoxAuthor = $('#searchBoxAuthor');
    $submitButton = $('#submit');
    return $submitButton.click(function(event) {
      var url;
      event.preventDefault();
      $contentDiv.empty();
      url = buildQuery($searchBoxGenre, $searchBoxTitle, $searchBoxAuthor);
      console.log(url);
      return $.get(url, function(data) {
        var $item, $row, i, index, item, len, post_title, ref, results;
        ref = data.results;
        results = [];
        for (index = i = 0, len = ref.length; i < len; index = ++i) {
          item = ref[index];
          if (index % 4 === 0) {
            if (typeof $row !== "undefined" && $row !== null) {
              $contentDiv.append($row);
            }
            $row = $("<div class='row'></div>");
          }
          post_title = item.post_title.split(' ').slice(0, 5).join(' ');
          $item = $("<div class='item col-md-3'> <a target='_blank' href='" + item.post_url + "'> <h3 class='itemTitle'>" + post_title + "</h3> <img src='" + item.item_image_url_large + "' alt='" + item.item_title + "'> </a> </div>");
          $row.append($item);
          if (index === data.results.length - 1) {
            $contentDiv.append($row);
          }
          results.push(console.log(item));
        }
        return results;
      });
    });
  });

  buildQuery = function($searchBoxGenre, $searchBoxTitle, $searchBoxAuthor) {
    var author, genre, title, url;
    genre = $searchBoxGenre.val();
    title = $searchBoxTitle.val();
    author = $searchBoxAuthor.val();
    url = baseURL + '?';
    if (genre !== '') {
      url += 'genre=' + genre + '&';
    }
    if (title !== '') {
      url += 'title=' + title + '&';
    }
    if (author !== '') {
      url += 'author=' + author + '&';
    }
    return url;
  };

}).call(this);
