// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var $searchBox, $submitButton, baseURL;
    baseURL = 'https://marginal-review-api.herokuapp.com/api/v1/reviews';
    $searchBox = $('#searchBox');
    $submitButton = $('#submit');
    return $submitButton.click(function(event) {
      var query;
      event.preventDefault();
      query = $searchBox.val();
      return $.get(baseURL + '?genre=' + query, function(data) {
        return console.log(data);
      });
    });
  });

}).call(this);
