baseURL = 'https://marginal-review-api.herokuapp.com/api/v1/reviews'

$(document).ready ->

    $('#searchBoxGenre').typeahead(
        {hint: true, highlight: true, minLength: 1},
        {name: 'genres', limit:10, source:substringMatcher(genres)}
    )

    $('#searchBoxTitle').typeahead(
        {hint: true, highlight: true, minLength: 1},
        {name: 'genres', limit:10, source:substringMatcher(genres)}
    )

    $('#searchBoxAuthor').typeahead(
        {hint: true, highlight: true, minLength: 1},
        {name: 'genres', limit:10, source:substringMatcher(genres)}
    )

    $contentDiv = $('#content')
    $('#submit').click (event) ->
        event.preventDefault()
        $contentDiv.empty()
        url = buildQuery()
        $.get url, (data) ->
            rows = buildRows(data.results.length, 4)
            for item, index in data.results
                $item = buildItemDiv(item)
                rows[index//4].append($item)
            $contentDiv.append($row) for $row in rows



buildRows = (numItems, columnCount) ->
    numRows = Math.ceil(numItems/columnCount)
    $("<div class='row'></div>") for [0...numRows]


buildItemDiv = (item) ->
    post_title = item.post_title.split(' ')[0..4].join(' ')
    $item = $("<div class='item col-md-3'>
                <a target='_blank' href='#{item.post_url}'>
                 <h3 class='itemTitle'>#{post_title}</h3>
                 <img src='#{item.item_image_url_large}' alt='#{item.item_title}'>
                </a>
              </div>")


buildQuery =  ->
    genre = $('#searchBoxGenre').val()
    title = $('#searchBoxTitle').val()
    author = $('#searchBoxAuthor').val()
    url = baseURL + '?'
    url += 'genre='+genre+'&' if genre isnt ''
    url += 'title='+title+'&' if title isnt ''
    url += 'author='+author+'&' if author isnt ''
    url


substringMatcher = (strs) ->
    (q, cb) ->
        console.log 'hey oh'
        substrRegex = new RegExp(q, 'i')
        matches = (str for str in strs when substrRegex.test(str))
        cb(matches)


genres = [
    "Economics"
    "Reference"
    "United States"
    "Literary"
    "Economic History"
    "History"
    "Economic Conditions"
    "Theory"
    "Social Sciences"
    "General"
    "Economic Policy"
    "Economic Policy & Development"
    "Movies"
    "World"
    "Contemporary"
    "Drama"
    "Sociology"
    "Political Science"
    "Pop"
    "Political"
    "Development & Growth"
    "Political Economy"
    "Indie & Art House"
    "Europe"
    "Technology"
    "Rock"
    "History & Theory"
    "Classics"
    "Economic Theory"
    "Public Policy"
    "Finance"
    "History & Philosophy"
    "Memoirs"
    "Classical"
    "Authors"
    "Foreign Films"
    "Globalization"
    "Cultural"
    "Popular Culture"
    "Business & Money"
    "Education & Reference"
    "Macroeconomics"
    "Historical"
    "Entrepreneurship"
    "European"
    "International"
    "Management"
    "Social Psychology & Interactions"
    "Historical Study & Educational Resources"
    "Criticism & Theory"
    "Mystery & Thrillers"
    "Chamber Music"
    "Conservatism & Liberalism"
    "Business Development"
    "Government & Business"
    "Consumer Behavior"
    "Environmental Economics"
    "Business & Finance"
    "Essays"
    "Action & Adventure"
    "Ethics"
    "Science Fiction"
    "Cognitive Psychology"
    "Money & Monetary Policy"
    "Ethics & Morality"
    "Industries"
    "Planning & Forecasting"
    "State & Local"
    "Military"
    "Great Britain"
    "Comedy"
    "Asian"
    "VHS Custom Stores"
    "Symphonies"
    "History & Criticism"
    "Philosophy"
    "Romance"
    "Microeconomics"
    "Company Profiles"
    "Travel Writing"
    "Free Enterprise"
    "Human Resources"
    "Science & Mathematics"
    "Science Fiction & Fantasy"
    "Decision-Making & Problem Solving"
    "Decision Making"
    "Poverty"
    "Human Geography"
    "Public Affairs & Policy"
    "Business"
    "China"
    "Innovation"
    "Democracy"
    "Banks & Banking"
    "Law"
    "Urban"
    "Criminology"
    "Evolution"
    "Success"
    "Health, Fitness & Dieting"
    "Middle Eastern"
    "Women"
    "Literature"
    "Civilization & Culture"
    "Class"
    "Food Science"
    "Asia"
    "Computers & Technology"
    "Humor & Entertainment"
    "Social Policy"
    "Criticism"
    "Comparative"
    "Indie Rock"
    "Fantasy"
    "Psychology"
    "Anthropology"
    "Political Ideologies"
    "Cognitive"
    "Government"
    "Commentary & Opinion"
    "International Relations"
    "Psychology & Counseling"
    "Econometrics"
    "Social Services & Welfare"
    "Subjects"
    "History & Surveys"
    "All"
    "World War II"
    "Operettas"
    "Africa"
    "Adult Alternative"
    "Political History"
    "Investing"
    "Nonprofit Organizations & Charities"
    "Environmental Science"
    "Marriage & Family"
    "Movements & Periods"
    "India"
    "International Business"
    "Jazz"
    "Agriculture"
    "Singer-Songwriters"
    "Russia"
    "TV"
    "All Titles"
    "All Sony Pictures Titles"
    "Caribbean & Latin American"
    "International & World Politics"
    "Middle East"
    "Motivational"
    "Biology"
    "British & Irish"
    "Environmental Policy"
    "Research"
    "National & International Security"
    "Income Inequality"
    "Horror"
    "Communication & Media Studies"
    "Conservation"
    "Commerce"
    "Hospitality, Travel & Tourism"
    "Germany"
    "Family Life"
    "Vocal Pop"
    "Personal Finance"
    "Computer Science"
    "Religion & Spirituality"
    "Communications"
    "Leadership"
    "Opera & Classical Vocal"
    "Higher & Continuing Education"
    "Kids & Family"
    "Probability & Statistics"
    "Human Rights"
    "Studio Specials"
    "Behavioral Sciences"
    "Statistics"
    "Literature & Fiction"
    "Folk Rock"
    "Psychological Thrillers"
    "Travel"
    "Women in History"
    "Health Policy"
    "Happiness"
    "Business of Art"
    "Scientists"
    "Short Stories"
    "Elections"
    "Discrimination & Racism"
    "Documentary"
    "Education"
    "Systems & Planning"
    "Modern"
    "Dance Pop"
    "Ethnic Studies"
    "Applied Psychology"
    "Health Care Delivery"
    "Biology & Life Sciences"
    "Communism & Socialism"
    "Comparative Politics"
    "Non-US Legal Systems"
    "Trades & Tariffs"
    "Robotics & Automation"
    "Folk"
    "National"
    "Ecology"
    "Suspense"
    "Environmentalism"
    "African-American Studies"
    "France"
    "Mental Health"
    "Reform & Policy"
    "Restaurant & Food"
    "Anatomy"
    "Civil Rights & Liberties"
    "Philosophers"
    "World Music"
    "Accounting"
    "Alternative Rock"
    "Personality"
    "Adventure"
    "Self-Help"
    "Chinese"
    "Public Finance"
    "Regional"
    "Album-Oriented Rock (AOR)"
    "Transportation"
    "Actors & Entertainers"
    "Violence in Society"
    "Demography"
    "German"
    "Television"
    "Personal Transformation"
    "Climatology"
    "Linguistics"
    "Contemporary Folk"
    "Military & War"
    "African"
    "Political Parties"
    "Bebop"
    "Japan"
    "Mystery"
    "Workplace Culture"
    "Emigration & Immigration"
    "Marketing"
    "Presidents & Heads of State"
    "Art House & International"
    "Banking"
    "Architecture"
    "French"
    "Information Management"
    "Biographies & Memoirs"
    "England"
    "Archaeology"
    "Dance & Electronic"
    "Avant Garde & Free Jazz"
    "Parenting"
    "Russian & Former Soviet Union"
    "Teen & Young Adult"
    "Sustainable Development"
    "Physics"
    "Diplomacy"
    "Pop Rap"
    "Sports"
    "City Planning & Urban Development"
    "Neuropsychology"
    "Concertos"
    "Urban Planning & Development"
    "Poetry"
    "Anthologies"
    "Engineering"
    "World War I"
    "Brazil"
    "Mathematics"
    "All Fox Titles"
    "Aesthetics"
    "Labor & Industrial Relations"
    "Church & State"
    "State"
    "Cosmology"
    "Weather"
    "Religion, Politics & State"
    "Science & Math"
    "Rivers"
    "Internet, Groupware, & Telecommunications"
    "Musicals"
    "Jewish"
    "Sonatinas"
    "Journalism & Nonfiction"
    "Other Diets"
    "Sexuality"
    "Social Theory"
    "Interpersonal Relations"
    "High Tech"
    "War"
    "Religious"
    "Arts & Photography"
    "Natural History"
    "Special Editions"
    "Christianity"
    "Composers & Musicians"
    "Minority Studies"
    "Genetics"
    "Guides"
    "Business Ethics"
    "Urban & Regional"
    "Progressive Rock"
    "Energy Production & Extraction"
    "Political Freedom"
    "Spanish & Portuguese"
    "Media & Communications"
    "Special Interest"
    "All MGM Titles"
    "Traditional Folk"
    "Medical"
    "Biotechnology"
    "Terrorism"
    "Americana"
    "Geography"
    "Journalists"
    "Introduction"
    "Clinical Psychology"
    "U.S. Presidents"
    "Exercise & Fitness"
    "Specialty Boutique"
    "Paranormal & Urban"
    "Foreign Language Study & Reference"
    "Espionage"
    "Political Advocacy"
    "Processes & Infrastructure"
    "Social Scientists & Psychologists"
    "Investments & Securities"
    "Family Saga"
    "Music"
    "TV, Movie, Video Game Adaptations"
    "Corporate Finance"
    "Ideologies & Doctrines"
    "Oil & Energy"
    "Legal History"
    "Nuclear"
    "Mammals"
    "Techno"
    "Nutrition"
    "E-Commerce"
    "Travelers & Explorers"
    "Country"
    "Baseball"
    "Metaphysical & Visionary"
    "Blues Rock"
    "Artists, Architects & Photographers"
    "Women's Studies"
    "Suites"
    "Contemporary Women"
    "Chess"
    "Anatomy & Physiology"
    "Customs & Traditions"
    "Electronica"
    "Humorous"
    "Coming of Age"
    "Historic"
    "Industrial, Manufacturing & Operational Systems"
    "Social Philosophy"
    "Epic"
    "Disaster Relief"
    "Game Theory"
    "Sonatas"
    "Blues"
    "Country Rock"
    "Occupational & Organizational"
    "Russian"
    "Neuroscience"
    "Urban & Land Use Planning"
    "Egypt"
    "Australia & New Zealand"
    "Child Psychology"
    "Weight Loss"
    "Psychoanalysis"
    "Executive Branch"
    "Today's Country"
    "Modern Postbebop"
    "Public Affairs & Administration"
    "Fiction"
    "Emotions"
    "Australia & Oceania"
    "Satire"
    "Industrial"
    "Latin Pop"
    "All Lionsgate Titles"
    "Latin Music"
    "Fantasies"
    "Church History"
    "Japanese"
    "Law Enforcement"
    "Sex"
    "Animation"
    "4-for-3 DVD"
    "Global"
    "Rome"
    "Soul"
    "Organized Crime"
    "Americas"
    "Motivation & Self-Improvement"
    "Astronomy"
    "Real Estate"
    "Telecommunications & Sensors"
    "Indian"
    "Environmental"
    "Patents & Inventions"
    "Natural Resources"
    "Italy"
    "New, Used & Rental Textbooks"
    "Latin America"
    "Asian American Studies"
    "Revolution & Founding"
    "Sports & Outdoors"
    "Advertising"
    "Politics & Government"
    "Epidemiology"
    "Earth Sciences"
    "Space Opera"
    "Feminist Theory"
    "Afro Brazilian"
    "Sacred & Religious"
    "Property"
    "Boxed Sets"
    "Shakespeare"
    "Regional Planning"
    "Islam"
    "Inflation"
    "African-American & Black"
    "Humanism"
    "Consumer Guides"
    "Biological Sciences"
    "Canada"
    "Performing Arts"
    "Reggae"
    "Business Culture"
    "Character Pieces"
    "Bluegrass"
    "Religious Studies"
    "New Age"
    "Holocaust"
    "Canadian"
    "Civil Procedure"
    "Turkey"
    "Israel & Palestine"
    "Biographies"
    "Pharmacology"
    "Fugues"
    "Popular"
    "Murder & Mayhem"
    "Behavioral Psychology"
    "Taxation"
    "Writing"
    "Manufacturing"
    "Biographical"
    "Iraq War"
    "Humor"
    "Metal"
    "East Coast"
    "Preludes"
    "Communication Policy"
    "Animal Behavior & Communication"
    "Comparative Religion"
    "Foreign Exchange"
    "Art"
    "Franchising"
    "Classic Country"
    "Intellectual Property"
    "Fauna"
    "Urban Life"
    "Torts"
    "Industrial Relations"
    "Mathematical Physics"
    "Communicable Diseases"
    "Geology"
    "Classic Rock"
    "Southeast"
    "Sony Pictures Classics"
    "Civil Rights"
    "Hospital Administration"
    "Dystopian"
    "Departments"
    "Compatible Devices"
    "Mexico"
    "Old Testament"
    "Colonial Period"
    "Culinary"
    "Administrative Law"
    "Sci-Fi & Fantasy"
    "Native American"
    "Creativity & Genius"
    "DTS"
    "All Universal Studios Titles"
    "New Business Enterprises"
    "Individual Artists"
    "North"
    "Ancient Civilizations"
    "Civics & Citizenship"
    "English Literature"]
